---
booktitle: Proceedings of the 6th Machine Learning for Healthcare Conference
volume: '149'
shortname: MLHC
year: '2021'
start: 2021-08-06
end: 2021-08-07
published: 2021-10-21
conference_number: '6'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: MLHC-2021
month: 0
cycles: false
bibtex_editor: Jung, Ken and Yeung, Serena and Sendak, Mark and Sjoding, Michael and
  Ranganath, Rajesh
editor:
- given: Ken
  family: Jung
- given: Serena
  family: Yeung
- given: Mark
  family: Sendak
- given: Michael
  family: Sjoding
- given: Rajesh
  family: Ranganath
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 6th Machine Learning for Healthcare Conference
    Held in Virtual on 06-07 August 2021

  Published as Volume 149 by the Proceedings of Machine Learning Research on 21 October 2021.

  Volume Edited by:
    Ken Jung
    Serena Yeung
    Mark Sendak
    Michael Sjoding
    Rajesh Ranganath

  Series Editors:
    Neil D. Lawrence
    * Mark Reid
date_str: 06--07 Aug
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v149"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v149
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v149
email: ''
conference:
  name: Machine Learning for Healthcare Conference
  url: http://mlforhc.org/
  location: Virtual
  dates:
  - 2021-08-06
  - 2021-08-07
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v149/mlhc21.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v149/mlhc21.bib
